// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:author": {
    params: {
      "author": string;
    };
  };
  "/:author/app.scribe.site": {
    params: {
      "author": string;
    };
  };
  "/:author/app.scribe.site/:siteRkey": {
    params: {
      "author": string;
      "siteRkey": string;
    };
  };
  "/:author/app.scribe.site/:siteRkey/:groupSlug": {
    params: {
      "author": string;
      "siteRkey": string;
      "groupSlug": string;
    };
  };
  "/:author/app.scribe.site/:siteRkey/:groupSlug/:articleRkey": {
    params: {
      "author": string;
      "siteRkey": string;
      "groupSlug": string;
      "articleRkey": string;
    };
  };
  "/:author/app.scribe.article": {
    params: {
      "author": string;
    };
  };
  "/:author/app.scribe.article/:articleRkey": {
    params: {
      "author": string;
      "articleRkey": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/:author" | "/:author/app.scribe.site" | "/:author/app.scribe.site/:siteRkey" | "/:author/app.scribe.site/:siteRkey/:groupSlug" | "/:author/app.scribe.site/:siteRkey/:groupSlug/:articleRkey" | "/:author/app.scribe.article" | "/:author/app.scribe.article/:articleRkey";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/author.tsx": {
    id: "routes/author";
    page: "/:author" | "/:author/app.scribe.site" | "/:author/app.scribe.site/:siteRkey" | "/:author/app.scribe.site/:siteRkey/:groupSlug" | "/:author/app.scribe.site/:siteRkey/:groupSlug/:articleRkey" | "/:author/app.scribe.article" | "/:author/app.scribe.article/:articleRkey";
  };
  "routes/tree.tsx": {
    id: "routes/tree";
    page: "/:author";
  };
  "routes/tree-alt.tsx": {
    id: "routes/tree-alt";
    page: "/:author/app.scribe.site";
  };
  "routes/site.tsx": {
    id: "routes/site";
    page: "/:author/app.scribe.site/:siteRkey";
  };
  "routes/group.tsx": {
    id: "routes/group";
    page: "/:author/app.scribe.site/:siteRkey/:groupSlug";
  };
  "routes/article-site.tsx": {
    id: "routes/article-site";
    page: "/:author/app.scribe.site/:siteRkey/:groupSlug/:articleRkey";
  };
  "routes/articles.tsx": {
    id: "routes/articles";
    page: "/:author/app.scribe.article";
  };
  "routes/article.tsx": {
    id: "routes/article";
    page: "/:author/app.scribe.article/:articleRkey";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/author": typeof import("./app/routes/author.tsx");
  "routes/tree": typeof import("./app/routes/tree.tsx");
  "routes/tree-alt": typeof import("./app/routes/tree-alt.tsx");
  "routes/site": typeof import("./app/routes/site.tsx");
  "routes/group": typeof import("./app/routes/group.tsx");
  "routes/article-site": typeof import("./app/routes/article-site.tsx");
  "routes/articles": typeof import("./app/routes/articles.tsx");
  "routes/article": typeof import("./app/routes/article.tsx");
};